// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgu1NkDjixMbtNpe6GX4GJWK8ZJ8mUlyo',
    appId: '1:237449985042:android:26805f7febdce07c966ccb',
    messagingSenderId: '237449985042',
    projectId: 'taskssphere',
    storageBucket: 'taskssphere.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3r7JwHEmhnJjebh95PMCSAenbeJS4IdE',
    appId: '1:237449985042:ios:180cf20b0ffead61966ccb',
    messagingSenderId: '237449985042',
    projectId: 'taskssphere',
    storageBucket: 'taskssphere.firebasestorage.app',
    iosBundleId: 'de.codesphere.taskssphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3r7JwHEmhnJjebh95PMCSAenbeJS4IdE',
    appId: '1:237449985042:ios:180cf20b0ffead61966ccb',
    messagingSenderId: '237449985042',
    projectId: 'taskssphere',
    storageBucket: 'taskssphere.firebasestorage.app',
    iosBundleId: 'de.codesphere.taskssphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl2JzQcs1fq7mzQA1NXWOix4I7cnE_lUc',
    appId: '1:237449985042:web:302cad2df444f926966ccb',
    messagingSenderId: '237449985042',
    projectId: 'taskssphere',
    authDomain: 'taskssphere.firebaseapp.com',
    storageBucket: 'taskssphere.firebasestorage.app',
    measurementId: 'G-2S8MDWMTSH',
  );

}
